/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto2.proyecto2_topicos;


import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtils;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.SpiderWebPlot;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileOutputStream;

/**
 *
 * @author Joela
 */
public class FrameTablas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameTablas.class.getName());

    /**
     * Creates new form FrameTablas
     */
    private JFreeChart chartLineas;
    private JFreeChart chartRadar;
    private JFreeChart chartArea;
    private Reporte rep;

    private String textoJoin = "El presente reporte tabular se genera a partir de la unificación (JOIN) "
            + "de los catálogos geográficos estatales y la tipología de delitos "
            + "con la tabla transaccional de incidencias. Esto permite transformar "
            + "identificadores numéricos en información legible para su análisis.";
    
    private DefaultTableModel modeloTabla;
    
    public FrameTablas() {
        initComponents();
        rep = new Reporte();
        modeloTabla = rep.obtenerDatosTabla();
        jTableConsulta.setModel(modeloTabla);
        this.generarGraficos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaExplicacion = new javax.swing.JTextArea();
        jPanelGrafico1 = new javax.swing.JPanel();
        jPanelGrafico2 = new javax.swing.JPanel();
        jPanelGrafico3 = new javax.swing.JPanel();
        jButtonGenerarPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla Consultas"));

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableConsulta);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Explicacion"));

        jTextAreaExplicacion.setEditable(false);
        jTextAreaExplicacion.setColumns(20);
        jTextAreaExplicacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaExplicacion.setRows(5);
        jTextAreaExplicacion.setText("El presente reporte tabular se genera a partir de la unificación (JOIN) de los \ncatálogos geográficos estatales y la tipología de delitos con la tabla \ntransaccional de incidencias. Esto permite transformar identificadores \nnuméricos en información legible, mostrando la relación directa entre un \nestado, el tipo de crimen y la cantidad de casos ocurridos en un año \nespecífico, facilitando así el análisis de la seguridad pública.");
        jTextAreaExplicacion.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextAreaExplicacion);

        jPanelGrafico1.setBorder(javax.swing.BorderFactory.createTitledBorder("Grafico 1"));

        javax.swing.GroupLayout jPanelGrafico1Layout = new javax.swing.GroupLayout(jPanelGrafico1);
        jPanelGrafico1.setLayout(jPanelGrafico1Layout);
        jPanelGrafico1Layout.setHorizontalGroup(
            jPanelGrafico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanelGrafico1Layout.setVerticalGroup(
            jPanelGrafico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jPanelGrafico2.setBorder(javax.swing.BorderFactory.createTitledBorder("Grafico 2"));

        javax.swing.GroupLayout jPanelGrafico2Layout = new javax.swing.GroupLayout(jPanelGrafico2);
        jPanelGrafico2.setLayout(jPanelGrafico2Layout);
        jPanelGrafico2Layout.setHorizontalGroup(
            jPanelGrafico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanelGrafico2Layout.setVerticalGroup(
            jPanelGrafico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelGrafico3.setBorder(javax.swing.BorderFactory.createTitledBorder("Grafico 3"));

        javax.swing.GroupLayout jPanelGrafico3Layout = new javax.swing.GroupLayout(jPanelGrafico3);
        jPanelGrafico3.setLayout(jPanelGrafico3Layout);
        jPanelGrafico3Layout.setHorizontalGroup(
            jPanelGrafico3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanelGrafico3Layout.setVerticalGroup(
            jPanelGrafico3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButtonGenerarPDF.setText("Generar PDF");
        jButtonGenerarPDF.addActionListener(this::jButtonGenerarPDFActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelGrafico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelGrafico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jPanelGrafico3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addComponent(jButtonGenerarPDF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelGrafico2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGrafico3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGrafico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGenerarPDF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarPDFActionPerformed
        // TODO add your handling code here:
        try {
            // Guardar gráficas como imágenes temporales
            ChartUtils.saveChartAsPNG(new File("grafica1.png"), chartLineas, 500, 300);
            ChartUtils.saveChartAsPNG(new File("grafica2.png"), chartRadar, 500, 300);
            ChartUtils.saveChartAsPNG(new File("grafica3.png"), chartArea, 500, 300);

            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream("Reporte_Seguridad_Publica.pdf"));
            document.open();

            // Título
            Font fontTitulo = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
            Paragraph titulo = new Paragraph("Reporte de Incidencia Delictiva", fontTitulo);
            titulo.setAlignment(Element.ALIGN_CENTER);
            document.add(titulo);
            document.add(new Paragraph("\n"));

            // Párrafo Explicativo
            Font fontParrafo = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL);
            Paragraph parrafo = new Paragraph(textoJoin, fontParrafo);
            parrafo.setAlignment(Element.ALIGN_JUSTIFIED);
            document.add(parrafo);
            document.add(new Paragraph("\n"));

            // Tabla PDF
            PdfPTable pdfTable = new PdfPTable(modeloTabla.getColumnCount());
            pdfTable.setWidthPercentage(100);
            
            // Encabezados
            for (int i = 0; i < modeloTabla.getColumnCount(); i++) {
                pdfTable.addCell(new PdfPCell(new Paragraph(modeloTabla.getColumnName(i), new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD))));
            }
            // Datos
            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                for (int j = 0; j < modeloTabla.getColumnCount(); j++) {
                    pdfTable.addCell(modeloTabla.getValueAt(i, j).toString());
                }
            }
            document.add(pdfTable);
            
            // Gráficas en nueva página
            document.newPage();
            document.add(new Paragraph("Análisis Gráfico de los Datos\n\n", fontTitulo));
            
            String[] imagenes = {"grafica1.png", "grafica2.png", "grafica3.png"};
            for (String imgRuta : imagenes) {
                Image img = Image.getInstance(imgRuta);
                img.setAlignment(Element.ALIGN_CENTER);
                img.scalePercent(80f);
                document.add(img);
                document.add(new Paragraph("\n"));
                new File(imgRuta).delete(); // Limpieza de archivos temporales
            }

            document.close();
            JOptionPane.showMessageDialog(this, "¡PDF generado exitosamente!", "Operación Exitosa", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al generar PDF: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButtonGenerarPDFActionPerformed

    private void generarGraficos(){
        // 1. Líneas: tendencia de cada delito
        chartLineas = ChartFactory.createLineChart("Tendencia por delito (Coahuila)", "Año", "Casos",
                rep.obtenerDatosLineas(), PlotOrientation.VERTICAL, true, true, false);
        ((org.jfree.chart.renderer.category.LineAndShapeRenderer)
                chartLineas.getCategoryPlot().getRenderer()).setDefaultShapesVisible(true);

        // 2. Radar: comparativo entre años
        SpiderWebPlot plot = new SpiderWebPlot(rep.obtenerDatosRadar());
        plot.setInteriorGap(0.35); // deja espacio para las etiquetas largas
        plot.setLabelFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 9));
        chartRadar = new JFreeChart("Comparativo por año",
                                    JFreeChart.DEFAULT_TITLE_FONT, plot, true);

        // 3. Área apilada: aportación de cada delito al total del año
        chartArea = ChartFactory.createStackedAreaChart(
                "Total de casos por año", "Año", "Casos",
                rep.obtenerDatosArea(), PlotOrientation.VERTICAL, true, true, false);

        // Fuentes pequeñas para paneles de ~310 px
        java.awt.Font fuenteTitulo  = new java.awt.Font("SansSerif", java.awt.Font.BOLD, 12);
        java.awt.Font fuenteLeyenda = new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 9);
        for (JFreeChart c : new JFreeChart[]{chartLineas, chartRadar, chartArea}) {
            c.getTitle().setFont(fuenteTitulo);
            c.getLegend().setItemFont(fuenteLeyenda);
        }

        ChartPanel panelChart1 = new ChartPanel(chartLineas);
        ChartPanel panelChart2 = new ChartPanel(chartRadar);
        ChartPanel panelChart3 = new ChartPanel(chartArea);

        java.awt.Dimension tam = new java.awt.Dimension(306, 300);
        for (ChartPanel cp : new ChartPanel[]{panelChart1, panelChart2, panelChart3}) {
            cp.setPreferredSize(tam);
            cp.setMinimumSize(new java.awt.Dimension(100, 100));
            cp.setMinimumDrawWidth(100);
            cp.setMinimumDrawHeight(100);
        }

        jPanelGrafico1.setLayout(new java.awt.BorderLayout());
        jPanelGrafico2.setLayout(new java.awt.BorderLayout());
        jPanelGrafico3.setLayout(new java.awt.BorderLayout());
        jPanelGrafico1.add(panelChart1, java.awt.BorderLayout.CENTER);
        jPanelGrafico2.add(panelChart2, java.awt.BorderLayout.CENTER);
        jPanelGrafico3.add(panelChart3, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameTablas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerarPDF;
    private javax.swing.JPanel jPanelGrafico1;
    private javax.swing.JPanel jPanelGrafico2;
    private javax.swing.JPanel jPanelGrafico3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTextArea jTextAreaExplicacion;
    // End of variables declaration//GEN-END:variables
}
